### ISSUE TITLE
URL could not be retrieved (@@practice/reedeem-voucher)

### ISSUE THREAD

**Issue by njscheffler** [Siyavula/monassis-issues#2] opened 2014-03-07 08:59 UTC
Somerset College learners are reportedly having trouble logging in on Everything Science.  However, that description of the problem does not match the screen shot they submitted (see below), which seems to show them trying to access the redeem a voucher page specifically and the service is unable to retrieve the URL.

Unable to replicate the problem.

Requested more information to try and clear up the discrepancy between these 2 pieces of info.  Regardless, the screen shot indicates that there is a problem, even if not the one they are describing. 

![url could not be retrieved](https://f.cloud.github.com/assets/4162049/2355220/8b30a502-a5d5-11e3-84f9-0a71b1003aa7.jpg)

**Comment by cscheffler** [comment] 2014-03-07 09:11
I can't reproduce it either. My best guess is that there was a load shedding problem again. If more issues like this get reported, just paste them here so that we can keep monitoring what's going on.

**Comment by njscheffler** [comment] 2014-03-07 09:50
Emailed teacher suggesting load-shedding as a possible cause and asked to be kept updated.

**Comment by cscheffler** [comment] 2014-05-09 07:28
Closing this issue since the problem has never recurred and was probably related to network problems at the time.

**Closed as completed by cscheffler** 2014-05-09 07:28 UTC
Labels: System
